server:
  port: 8080
spring:
  application:
    name: common
  profiles:
    include: druid
  mvc:
    servlet:
      path: /dev-api
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/common?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useAffectedRows=true
#    url: jdbc:h2:file:F:\h2\data\common;NON_KEYWORDS=USER;
#    url: jdbc:h2:file:F:\h2\data\common
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.h2.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  elasticsearch:
    uris: 127.0.0.1:9300
  sql:
    init:
      mode: never
      schema-locations: classpath*:sql/mysql/schema.sql
      data-locations: classpath*:sql/mysql/data.sql
#      schema-locations: classpath*:sql/h2/schema.sql
#      data-locations: classpath*:sql/h2/data.sql
#    time-zone: GMT+8
mybatis-plus:
  configuration:
    auto-mapping-unknown-column-behavior: warning
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
