server:
  port: 8080
spring:
  application:
    name: common
  profiles:
    include: druid
  mvc:
    servlet:
      path: /dev-api
  datasource:
    url: jdbc:mysql://localhost:3306/common?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: never
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql
