# druid config list
spring:
  datasource:
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 10
      max-wait: 60000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validation-query: select 1
      filters: stat,wall,slf4j
      #      连接回收的时候控制台打印信息
      log-abandoned: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        session-stat-enable: true
        profile-enable: true
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: root
        allow: 127.0.0.1
        url-pattern: /druid/*
      filter:
        wall:
          enabled: true
          db-type: mysql
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 100

