server:
  port: 8080
spring:
  application:
    name: common
  profiles:
    include: druid
  mvc:
    servlet:
      path: /dev-api
  datasource:
    url: jdbc:mysql://localhost:3306/common?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useAffectedRows=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: never
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
mybatis-plus:
  configuration:
    auto-mapping-unknown-column-behavior: warning
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
