spring:
  datasource:
    db1:
      url: jdbc:mysql://192.168.1.111:3306/ds1?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useAffectedRows=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      initialization-mode: never
      schema: classpath*:sql/schema.sql
      data: classpath*:sql/data.sql
    db2:
      url: jdbc:mysql://192.168.1.111:3306/ds2?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&useAffectedRows=true
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
      initialization-mode: never
      schema: classpath*:sql/schema.sql
      data: classpath*:sql/data.sql